### ISSUE TITLE
BUG: Possible to double book rooms 221, 222, 223, 224 & 233.

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/booking-app#317]
to replicate:

1. identify as an Admin/Staff from dept. ITP/IMA
2. pick a date in the future
3. select rooms 221, 222, 223, 224 & 233
4. select a four hour time slot
5. request Room Setup (voids auto approval) and submit request
6. click Book button
7. identify as an Admin/Staff from dept. ITP/IMA
8. choose same date as in step 2.
9. select rooms 221, 222, 223, 224 & 233
10. note that the previously requested booking does not appear on the calendars (enabling a double booking)![Image](https://github.com/user-attachments/assets/80f57066-c7be-4283-b43b-2ce5d37748e3)

![Image](https://github.com/user-attachments/assets/87b3a518-a4f0-4aa5-b625-2a5ccd5747ab)

![Image](https://github.com/user-attachments/assets/59ee6bd4-13ab-44b3-8b58-e68f0489599b)

![Image](https://github.com/user-attachments/assets/b32c6785-3db8-4222-9308-1443367a742d)

**Comment by lucia-gomez** [comment]
good catch, we were only loading calendar events once- when the app first loads. and never refreshing them even after the user makes a booking. so when you go to make a second booking without refreshing the page you don't see your new event on the calendar

**Comment by nopivnick** [comment]
we should load calendar events every time a user clicks on Book or Walk In, no?

**Comment by lucia-gomez** [comment]
yes now we are

**Comment by nopivnick** [comment]
@lucia-gomez I'm still seeing this bug when I submit a reservation for all rooms.

**Comment by lucia-gomez** [comment]
oh oops i forgot to push this change, facepalm

**Comment by nopivnick** [comment]
@lucia-gomez I'm still seeing this bug on Development.

**Comment by lucia-gomez** [comment]
Tried again and I'm not able to reproduce this. Also not able to reproduce the bug where Astro had to refresh the page to see the booking she just made appear on the calendar... assuming that's the same bug as this one.

**Comment by lucia-gomez** [comment]
Actually I was testing on my `feature/editBooking` branch where I did some refactoring of the "Book More" button. Let me finish that branch, merge it, and we can test again on main after that

**Comment by lucia-gomez** [comment]
fixed in #371 ?

**Comment by nopivnick** [comment]
still happening.

![Image](https://github.com/user-attachments/assets/0bf9586e-6083-4e00-a61e-30f845301c60)

**Comment by nopivnick** [comment]
hmm. I may have tested right before @lucia-gomez pushed #371 which may or may not have included a fix.

I'll try to replicate again.

**Comment by nopivnick** [comment]
looks like it's fixed!
